LDAP - Leave same images alone
madmatt/silverstripe-ldap pull request #2
Opened 2018-10-09 04:15 UTC by caffeineinc

When syncing large data sets, there's no point in overwriting images if
it is the same image. Instead, check the file hash of the old and new,
and overwrite if there's changes.

For large LDAP sources, this resolves an issue where the syncs are
incredibly file intensive.

2018-10-09 04:21 UTC, caffeineinc commented
@ishannz  You're right, it wasn't quite behaving correctly - I've made another change and created this new PR which contains both fixes. I'll commit that fix separately

2018-10-16 05:02 UTC, madmatt approved these changes
Awesome, thanks for this! Just a few super minor points.

2018-10-16 05:02 UTC, madmatt commented on docs/en/developer.md
>  This will allow users to change their AD password via the regular CMS "forgot password" forms, etc.
This line belongs to the changes above - can you shift your content down one line so this goes above it? :)

2018-10-16 05:02 UTC, madmatt commented on docs/en/developer.md
> +By default if attributes are present, and then missing in subsequent requests, they are ignored (non-descructive) by
_destructive_ ;-)

2018-10-16 05:02 UTC, madmatt commented on docs/en/developer.md
> +*Note*: This will mean syncs are desctructive, and data or attributes will be reset if missing from the master LDAP source
_destructive_

2018-10-16 05:02 UTC, madmatt commented on src/Services/LDAPService.php
> +                    if (method_exists($member->$field, "delete") && $member->$field->exists()) {
This only checks for `delete()` but then calls `deleteFile()`, meaning that it only actually works for the thumbnailphoto attribute (or any other `File` reference), right?

2018-10-16 05:02 UTC, madmatt commented on src/Services/LDAPService.php
> +                return;
This should be `return true` to indicate success (not needing to change the file is still a success)

2018-10-16 05:02 UTC, madmatt commented on tests/php/Model/LDAPFakeGateway.php
> +        // thumbnail images are raw png
They're actually raw JPEG/JFIF files, at least by default with ADFS

2018-10-16 05:04 UTC, madmatt requested changes
D'oh, meant to hit 'Request changes' rather than approve hehe, stupid green buttons are a dark UX anti-pattern :p

2018-10-30 00:56 UTC, madmatt commented
Closing this in favour of #3.

2018-10-30 00:56 UTC, closed without merging